//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Particle {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Particle.Messages", typeof(Messages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving Device Info for device {0}.
        /// </summary>
        internal static string ErrorRetreavingDeviceInfoForDevice {
            get {
                return ResourceManager.GetString("ErrorRetreavingDeviceInfoForDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving devices.
        /// </summary>
        internal static string ErrorRetrevingDevices {
            get {
                return ResourceManager.GetString("ErrorRetrevingDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passed variable must have a name.
        /// </summary>
        internal static string PassedVariableMustHaveAName {
            get {
                return ResourceManager.GetString("PassedVariableMustHaveAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Login Again.
        /// </summary>
        internal static string PleaseLoginAgain {
            get {
                return ResourceManager.GetString("PleaseLoginAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Response.
        /// </summary>
        internal static string UnexpectedResponse {
            get {
                return ResourceManager.GetString("UnexpectedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must authenticate before calling {0}.
        /// </summary>
        internal static string YouMusthAuthenticateBeforeCalling {
            get {
                return ResourceManager.GetString("YouMusthAuthenticateBeforeCalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must login before we can refresh the token.
        /// </summary>
        internal static string YouMustLoginBeforeRefreshingToken {
            get {
                return ResourceManager.GetString("YouMustLoginBeforeRefreshingToken", resourceCulture);
            }
        }
    }
}
